apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deploy
  labels:
    name: worker-deploy
    app: demo-voting-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-voting-app-worker
  template:
    metadata:
      name: worker-pod
      labels:
        app: demo-voting-app-worker
    spec:
      containers:
        - name: worker-app
          image: dockersamples/examplevotingapp_worker
